### ISSUE TITLE
EncointerWorker connection fails at TLS handshake (websocket close reason 1015)

### ISSUE THREAD

**Issue by clangenb** [encointer/encointer-js#86]
We never tested the worker since we added the TLS into the enclave with the self-signed certificate. I guess, the websocket lib has an issue with self-signed certs. See, error:

![image](https://github.com/encointer/encointer-js/assets/37865735/7fbe514e-19ae-4559-a7ab-28649c2de07b)

**Comment by clangenb** [comment]
On a local setup, I try to create the breakthrough but trying to run `worker.getShieldingKey`, which the following unit test: https://github.com/encointer/encointer-js/blob/d51cc2001ee63b96c43f4538526aba99f57408c1/packages/worker-api/src/worker.spec.ts#L60

On the js-side I get: 

```console
Error: WebSocket closed with reason: connection failed (1006).

    at EncointerWorker._handleClose (\\wsl$\Ubuntu\home\clang\code\encointer-js\node_modules\websocket-as-promised\src\index.js:407:19)
    at W3CWebSocket.listener (\\wsl$\Ubuntu\home\clang\code\encointer-js\node_modules\websocket-as-promised\src\index.js:340:64)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (\\wsl$\Ubuntu\home\clang\code\encointer-js\node_modules\yaeti\lib\EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (\\wsl$\Ubuntu\home\clang\code\encointer-js\node_modules\websocket\lib\W3CWebSocket.js:219:14)
    at WebSocketClient.<anonymous> (\\wsl$\Ubuntu\home\clang\code\encointer-js\node_modules\websocket\lib\W3CWebSocket.js:59:25)
    at WebSocketClient.emit (node:events:513:28)
    at ClientRequest.handleRequestError (\\wsl$\Ubuntu\home\clang\code\encointer-js\node_modules\websocket\lib\WebSocketClient.js:227:14)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketOnEnd (node:_http_client:526:9)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

On the worker side:
```console
[2024-03-29T18:00:19.999389Z ERROR itc_tls_websocket_server::connection] cannot process TLS packet(s), closing connection: CorruptMessage
```

Trying to get more info with better logs.

**Comment by clangenb** [comment]
This is how the stream looks for a successful trusted getter rpc from our rust client:

```console
[2024-03-29T21:55:11.410707Z TRACE itc_tls_websocket_server::ws_server] Connection (token Token(406)) activity event
[2024-03-29T21:55:11.410720Z TRACE itc_tls_websocket_server::connection] Connection (Token(406)) is readable
[2024-03-29T21:55:11.410737Z TRACE itc_tls_websocket_server::connection] Initialize connection 406
[2024-03-29T21:55:11.410830Z DEBUG itc_tls_websocket_server::connection] Initialized connection 406 successfully
[2024-03-29T21:55:11.411416Z DEBUG itc_tls_websocket_server::ws_server] Number of readiness events: 1
[2024-03-29T21:55:11.411468Z TRACE itc_tls_websocket_server::ws_server] Connection (token Token(406)) activity event
[2024-03-29T21:55:11.411481Z TRACE itc_tls_websocket_server::connection] Connection (Token(406)) is readable
[2024-03-29T21:55:11.411526Z TRACE itc_tls_websocket_server::connection] Read is possible for connection 406: true
[2024-03-29T21:55:11.411562Z TRACE itc_tls_websocket_server::connection] Got Message::Text on web-socket (connection 406), calling handler..
[2024-03-29T21:55:11.411594Z DEBUG enclave_runtime::rpc::worker_api_direct] worker_api_direct rpc was called: state_executeGetter
[2024-03-29T21:55:11.411774Z DEBUG ita_stf::getter] TrustedGetter free_balance
[2024-03-29T21:55:11.411809Z DEBUG ita_stf::getter] AccountInfo for 0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d is <wasm:stripped>
⣿STF⣿ 🔍 TrustedGetter query: free balance for ⣿⣿⣿ is ⣿⣿⣿
[2024-03-29T21:55:11.411865Z DEBUG itc_direct_rpc_server::rpc_ws_handler] RPC response string: Some("{\"jsonrpc\":\"2.0\",\"result\":\"0x4801400000c16ff286230000000000000000000000\",\"id\":1}")
```

**Comment by clangenb** [comment]
Ok, the errors were only thrown initially, when I still used the `ws` in the url instead of `wss`. Now it seems that the websocket connection is opened, but it is stale afterward. I believe that the JS-websocket is still expecting some final handshake, which is missing.
